export type TemplateGenerationCapsule = {
  id: string;
  family: string;
  requiredRoles: string[];
  forbidden: string[];
  htmlSkeleton: string;
  cssFoundation: string;
};

type CapsuleDefinition = {
  family: string;
  background: string;
  surface: string;
  ink: string;
  muted: string;
  border: string;
  shadow: string;
  radius: string;
  font: string;
  roles: string[];
  forbidden: string[];
  extra: string;
};

const skeletons: Record<string, string> = {
  product: `<body data-template-family="product"><header data-template-role="navigation"><a>Product</a><nav>...</nav><button data-template-role="primary-action">Create</button></header><main><section data-template-role="hero"><small>Workspace</small><h1>Primary product outcome</h1><p>Concise supporting explanation.</p></section><section data-template-role="content"><article>Primary work</article><article>Supporting status</article></section></main></body>`,
  data: `<body data-template-family="data"><header data-template-role="navigation">Global navigation</header><main><section data-template-role="hero"><h1>Operational overview</h1><button data-template-role="primary-action">Create</button></section><section data-template-role="metrics"><article>Metric</article><article>Metric</article><article>Metric</article></section><section data-template-role="table"><header>Priority work</header><table>...</table></section></main></body>`,
  board: `<body data-template-family="board"><header data-template-role="navigation">Project navigation</header><main><section data-template-role="hero"><h1>Collaborative workflow</h1><button data-template-role="primary-action">Add item</button></section><section data-template-role="board"><article>To do</article><article>In progress</article><article>Done</article></section></main></body>`,
  editorial: `<body data-template-family="editorial"><header data-template-role="masthead">Publication masthead</header><main><section data-template-role="hero"><small>Issue / 01</small><h1>Oversized editorial statement</h1></section><article data-template-role="story"><p>Long-form source content...</p></article><button data-template-role="primary-action">Continue reading</button></main></body>`,
  portfolio: `<body data-template-family="portfolio"><header data-template-role="navigation">Studio index</header><main><section data-template-role="hero"><small>Selected work</small><h1>Project-led statement</h1><button data-template-role="primary-action">View project</button></section><section data-template-role="gallery"><article>Project 01</article><article>Project 02</article><article>Project 03</article></section></main></body>`,
  mobile: `<body data-template-family="mobile"><main data-template-role="device"><header data-template-role="navigation">Mobile product</header><section data-template-role="hero"><h1>One clear mobile task</h1><p>Short supporting copy.</p></section><section data-template-role="content">Task content</section><button data-template-role="primary-action">Continue</button></main></body>`,
  skeuomorphic: `<body data-template-family="skeuomorphic"><main data-template-role="console"><header data-template-role="navigation">Physical control panel</header><section data-template-role="hero"><h1>Precision workspace</h1></section><section data-template-role="controls"><article>Dial and status</article><article>Inset display</article></section><button data-template-role="primary-action">Engage</button></main></body>`,
  spatial: `<body data-template-family="spatial"><div data-template-role="ambient-field"></div><header data-template-role="navigation">Glass navigation</header><main><section data-template-role="hero"><small>Spatial workspace</small><h1>Layered product story</h1><button data-template-role="primary-action">Enter</button></section><section data-template-role="content"><article>Foreground module</article><article>Depth module</article></section></main></body>`,
  experimental: `<body data-template-family="experimental"><header data-template-role="navigation">Experimental index</header><main><section data-template-role="hero"><small>Experiment / 01</small><h1>Oversized kinetic statement</h1><button data-template-role="primary-action">Explore</button></section><section data-template-role="stage"><article>Object 01</article><article>Object 02</article><article>Object 03</article></section></main></body>`,
  typelab: `<body data-template-family="typelab"><header data-template-role="navigation">Type laboratory</header><main><section data-template-role="hero"><h1>Variable type specimen</h1></section><aside data-template-role="controls">Axis controls</aside><section data-template-role="stage">Live typographic field</section><button data-template-role="primary-action">Apply type</button></main></body>`,
  collage: `<body data-template-family="collage"><header data-template-role="navigation">Alternative web index</header><main><section data-template-role="hero"><h1>Direct anti-grid statement</h1><button data-template-role="primary-action">Open window</button></section><section data-template-role="windows"><article>Window 01</article><article>Window 02</article><article>Window 03</article></section></main></body>`,
  exhibit: `<body data-template-family="exhibit"><header data-template-role="navigation">Exhibition wayfinding</header><main><section data-template-role="hero"><h1>Digital exhibition</h1></section><section data-template-role="stage"><article>Artwork 01</article><article>Artwork 02</article><article>Artwork 03</article></section><button data-template-role="primary-action">Enter room</button></main></body>`,
  canvas: `<body data-template-family="canvas"><header data-template-role="navigation">Canvas controls</header><main data-template-role="canvas"><section data-template-role="hero"><h1>Spatial idea field</h1></section><article>Cluster 01</article><article>Cluster 02</article><article>Cluster 03</article><button data-template-role="primary-action">Add object</button></main></body>`,
  carousel: `<body data-template-family="carousel"><div data-template-role="ambient-field"></div><header data-template-role="navigation">Collection index</header><main><section data-template-role="hero"><h1>Atmospheric collection</h1></section><section data-template-role="carousel"><article>Object 01</article><article>Object 02</article><article>Object 03</article></section><button data-template-role="primary-action">Next object</button></main></body>`,
  ascii: `<body data-template-family="ascii"><header data-template-role="navigation">Raster laboratory</header><main><section data-template-role="hero"><small>Digital material study</small><h1>Character-driven interface</h1><button data-template-role="primary-action">Switch mode</button></section><pre data-template-role="raster">ASCII / DITHER FIELD</pre></main></body>`,
};

const definitions: Record<string, CapsuleDefinition> = {
  minimal: { family:'product', background:'#f4f5f3', surface:'#ffffff', ink:'#18201c', muted:'#66706a', border:'rgba(24,32,28,.12)', shadow:'0 1px 2px rgba(20,28,24,.06)', radius:'10px', font:'Inter,Arial,sans-serif', roles:['navigation','hero','content','primary-action'], forbidden:['decorative gradients','equal-card dashboard'], extra:'[data-template-role="content"]{grid-template-columns:1.4fr .6fr}[data-template-role="hero"] h1{max-width:11ch}' },
  fluent: { family:'product', background:'linear-gradient(145deg,#edf1f7,#f8f5f2)', surface:'rgba(255,255,255,.82)', ink:'#24272d', muted:'#687080', border:'rgba(48,55,70,.12)', shadow:'0 16px 40px rgba(40,50,70,.10)', radius:'20px', font:'Segoe UI,Arial,sans-serif', roles:['navigation','hero','content','primary-action'], forbidden:['full-page transparency','heavy glass blur'], extra:'header,[data-template-role="content"]>article{backdrop-filter:blur(16px)}' },
  spectrum: { family:'product', background:'#e9e9eb', surface:'#f8f8f9', ink:'#202124', muted:'#67686d', border:'rgba(30,31,35,.16)', shadow:'0 4px 14px rgba(25,26,30,.08)', radius:'8px', font:'Arial,sans-serif', roles:['navigation','hero','content','primary-action'], forbidden:['decorative landing-page hero','oversized empty cards'], extra:'body{border-top:6px solid var(--compose-accent)}[data-template-role="content"]{grid-template-columns:.72fr 1.28fr}' },
  polaris: { family:'product', background:'#f3f3f3', surface:'#ffffff', ink:'#202223', muted:'#616866', border:'rgba(34,37,36,.12)', shadow:'0 2px 8px rgba(30,35,32,.08)', radius:'16px', font:'Inter,Arial,sans-serif', roles:['navigation','hero','content','primary-action'], forbidden:['abstract art direction','ambiguous status colors'], extra:'[data-template-role="content"]>article:first-child{border-left:4px solid #4a8b61}' },
  carbon: { family:'data', background:'#f4f4f4', surface:'#ffffff', ink:'#161616', muted:'#525252', border:'#d6d6d6', shadow:'none', radius:'0px', font:'Arial,sans-serif', roles:['navigation','hero','metrics','table','primary-action'], forbidden:['floating rounded cards','soft decorative shadows'], extra:'header{background:#161616!important;color:white}[data-template-role="metrics"]{grid-template-columns:repeat(3,1fr)}table{width:100%;border-collapse:collapse}th,td{padding:12px;border-bottom:1px solid #d6d6d6;text-align:left}' },
  console: { family:'data', background:'#080a0e', surface:'#13161c', ink:'#f4f6f8', muted:'#8b929d', border:'rgba(255,255,255,.13)', shadow:'0 0 30px rgba(88,105,255,.10)', radius:'8px', font:'ui-monospace,monospace', roles:['navigation','hero','metrics','table','primary-action'], forbidden:['pastel palette','large decorative imagery'], extra:'[data-template-role="metrics"]{grid-template-columns:repeat(3,1fr)}table{width:100%;color:inherit}body{font-variant-numeric:tabular-nums}' },
  atlassian: { family:'board', background:'#f1f2f4', surface:'#ffffff', ink:'#172b4d', muted:'#626f86', border:'rgba(23,43,77,.14)', shadow:'0 1px 2px rgba(9,30,66,.14)', radius:'10px', font:'Arial,sans-serif', roles:['navigation','hero','board','primary-action'], forbidden:['single marketing column','decorative glass'], extra:'[data-template-role="board"]{grid-template-columns:repeat(3,minmax(210px,1fr));overflow-x:auto;background:#dfe1e6;padding:12px}' },
  editorial: { family:'editorial', background:'#f4eddf', surface:'#fffaf0', ink:'#19171a', muted:'#676066', border:'rgba(25,23,26,.28)', shadow:'none', radius:'0px', font:'Georgia,"Songti SC",serif', roles:['masthead','hero','story','primary-action'], forbidden:['equal dashboard cards','app sidebar'], extra:'[data-template-role="masthead"]{border-bottom:1px solid currentColor}[data-template-role="hero"]{display:block}[data-template-role="hero"] h1{max-width:12ch;font-size:clamp(56px,10vw,132px);line-height:.82}[data-template-role="story"]{max-width:68ch;margin-left:auto}' },
  textgallery: { family:'editorial', background:'#f5efe3', surface:'#fffaf0', ink:'#17151a', muted:'#625d62', border:'rgba(23,21,26,.4)', shadow:'12px 18px 0 rgba(23,21,26,.08)', radius:'0px', font:'Georgia,"Songti SC",serif', roles:['masthead','hero','story','primary-action'], forbidden:['dashboard metrics','generic hero cards'], extra:'[data-template-role="hero"] h1{font-size:clamp(52px,9vw,120px);line-height:.84;text-decoration:underline;text-decoration-color:var(--compose-accent)}[data-template-role="story"]{columns:2;column-gap:48px}' },
  assembly: { family:'editorial', background:'#eee6d6', surface:'#fffaf0', ink:'#171419', muted:'#6d655e', border:'rgba(23,20,25,.32)', shadow:'8px 10px 0 rgba(23,20,25,.11)', radius:'0px', font:'Georgia,"Songti SC",serif', roles:['masthead','hero','story','primary-action'], forbidden:['static equal grid','rounded SaaS cards'], extra:'main{position:relative}section,article{transform:rotate(-.6deg)}[data-template-role="story"]{margin-left:20%;transform:translateY(-12px) rotate(.8deg)}' },
  portfolio: { family:'portfolio', background:'#121113', surface:'#201e22', ink:'#f7f3ee', muted:'#aaa3aa', border:'rgba(255,255,255,.18)', shadow:'0 30px 80px rgba(0,0,0,.35)', radius:'4px', font:'Helvetica,Arial,sans-serif', roles:['navigation','hero','gallery','primary-action'], forbidden:['admin dashboard','equal KPI cards'], extra:'[data-template-role="hero"] h1{max-width:10ch;font-size:clamp(64px,12vw,150px);line-height:.78}[data-template-role="gallery"]{grid-template-columns:1.6fr .8fr .6fr;align-items:end}[data-template-role="gallery"] article:nth-child(2){transform:translateY(42px)}' },
  soft: { family:'product', background:'#fbf1f2', surface:'#fff9f8', ink:'#342b31', muted:'#7f7178', border:'rgba(77,57,68,.10)', shadow:'0 18px 45px rgba(91,62,77,.12)', radius:'28px', font:'Avenir,Arial,sans-serif', roles:['navigation','hero','content','primary-action'], forbidden:['hard black borders','aggressive rotation'], extra:'[data-template-role="content"]>article:nth-child(2){background:#e6f2df}button{border-radius:999px!important}' },
  mobile: { family:'mobile', background:'#dfe5ed', surface:'#ffffff', ink:'#1f252b', muted:'#69727a', border:'rgba(31,37,43,.12)', shadow:'0 24px 70px rgba(30,39,48,.20)', radius:'26px', font:'-apple-system,Arial,sans-serif', roles:['device','navigation','hero','content','primary-action'], forbidden:['desktop dashboard grid','small touch targets'], extra:'[data-template-role="device"]{width:min(390px,100%);min-height:720px;margin:auto;padding:18px;background:#fff;border:8px solid #17191c;border-radius:42px}[data-template-role="primary-action"]{width:100%;min-height:52px}' },
  precision: { family:'skeuomorphic', background:'linear-gradient(145deg,#2b211a,#65442e)', surface:'linear-gradient(145deg,#d8c5a9,#a68b6c)', ink:'#241b15', muted:'#6b5848', border:'rgba(55,39,27,.45)', shadow:'inset 2px 2px 2px rgba(255,255,255,.7),inset -4px -5px 8px rgba(70,45,26,.3),0 12px 24px rgba(20,12,8,.28)', radius:'18px', font:'Rockwell,Georgia,serif', roles:['console','navigation','hero','controls','primary-action'], forbidden:['flat generic cards','inconsistent light sources'], extra:'[data-template-role="console"]{padding:28px;border:1px solid #8e7356;background:linear-gradient(120deg,#b9a183,#e5d3b7 45%,#a88b68);box-shadow:inset 0 0 0 4px rgba(70,48,30,.35),0 30px 80px rgba(0,0,0,.35)}[data-template-role="controls"] article:before{content:"";display:block;width:64px;height:64px;border-radius:50%;background:radial-gradient(circle at 35% 30%,#fff,#9d876c 42%,#3c2e23 70%,#d4bea0);box-shadow:var(--template-shadow)}' },
  spatial: { family:'spatial', background:'radial-gradient(circle at 15% 80%,#ff83ca 0 12%,transparent 34%),radial-gradient(circle at 88% 14%,#61e2ff 0 12%,transparent 32%),linear-gradient(145deg,#526cff,#d7c1ff 58%,#ffc2e4)', surface:'rgba(255,255,255,.15)', ink:'#171826', muted:'rgba(23,24,38,.62)', border:'rgba(255,255,255,.72)', shadow:'inset 1px 1px 2px rgba(255,255,255,.9),0 24px 60px rgba(48,37,110,.22)', radius:'28px', font:'Inter,Arial,sans-serif', roles:['ambient-field','navigation','hero','content','primary-action'], forbidden:['glass on every text block','opaque flat dashboard'], extra:'header,button,[data-template-role="content"]>article{backdrop-filter:blur(18px) saturate(135%);background:linear-gradient(145deg,rgba(255,255,255,.30),rgba(255,255,255,.08));border-color:rgba(255,255,255,.76)}[data-template-role="hero"] h1{font-size:clamp(62px,10vw,130px);line-height:.82}' },
  kinetic: { family:'experimental', background:'#f5f0e7', surface:'#171419', ink:'#171419', muted:'#686168', border:'#171419', shadow:'12px 12px 0 var(--compose-accent)', radius:'2px', font:'Arial Black,Arial,sans-serif', roles:['navigation','hero','stage','primary-action'], forbidden:['conventional centered SaaS hero','uniform cards'], extra:'[data-template-role="hero"] h1{max-width:9ch;font-size:clamp(72px,14vw,180px);line-height:.72;letter-spacing:-.09em}[data-template-role="stage"]{margin-top:-8vh;grid-template-columns:1.4fr .7fr .5fr;transform:rotate(-2deg)}[data-template-role="stage"] article{color:white}' },
  brutal: { family:'experimental', background:'#fff568', surface:'#ffffff', ink:'#111111', muted:'#3c3c3c', border:'#111111', shadow:'6px 6px 0 #111', radius:'0px', font:'Arial Black,Arial,sans-serif', roles:['navigation','hero','stage','primary-action'], forbidden:['soft shadows','low-contrast pastel text'], extra:'header,section,article,button{border:2px solid #111}[data-template-role="stage"]{grid-template-columns:repeat(3,1fr)}button:active{transform:translate(4px,4px);box-shadow:2px 2px 0 #111}' },
  typelab: { family:'typelab', background:'#f2f0eb', surface:'#ffffff', ink:'#111111', muted:'#66615d', border:'#111111', shadow:'none', radius:'0px', font:'Arial,sans-serif', roles:['navigation','hero','controls','stage','primary-action'], forbidden:['image-led gallery','decorative card grid'], extra:'.type-lab-shell{grid-template-columns:minmax(0,1fr) minmax(190px,260px)}.type-specimen{grid-column:1/-1;border-bottom:1px solid var(--template-border)}.type-specimen h1{max-width:9ch;font-family:"Arial Narrow",Arial,sans-serif;font-size:clamp(76px,13vw,176px);font-weight:900;font-stretch:condensed;line-height:.68;text-transform:uppercase}.type-specimen h1 span{display:block}.axis-panel{grid-row:2/4;grid-column:2;padding:18px;border-left:1px solid var(--template-border);align-content:start}.axis-panel article{display:grid;grid-template-columns:1fr auto;gap:8px;min-height:0!important;padding:14px 0!important;border:0!important;border-bottom:1px solid var(--template-border)!important;background:transparent!important}.axis-panel i{grid-column:1/-1;height:5px;background:color-mix(in srgb,var(--template-ink) 14%,transparent)}.axis-panel i:after{content:"";display:block;width:68%;height:100%;background:var(--compose-accent)}.type-stage{display:grid;grid-template-columns:1.35fr .65fr;gap:0!important;min-height:330px}.type-stage>article{display:flex;flex-direction:column;justify-content:space-between;min-height:330px;padding:20px!important;border-width:1px 0 1px 1px!important}.type-stage>article:first-child h2{max-width:8ch;font-family:"Arial Narrow",Arial,sans-serif;font-size:clamp(48px,7vw,92px);line-height:.78;text-transform:uppercase}.type-stage>article:last-child{background:var(--compose-accent);color:var(--compose-accent-contrast)}.type-stage p{margin-top:auto}.type-action{justify-self:start}' },
  altweb: { family:'collage', background:'#dfff73', surface:'#fffdf5', ink:'#111111', muted:'#4c4c45', border:'#111111', shadow:'8px 8px 0 #111', radius:'2px', font:'ui-monospace,monospace', roles:['navigation','hero','windows','primary-action'], forbidden:['perfectly aligned bento grid','subtle border-only UI'], extra:'[data-template-role="windows"]{position:relative;display:block;min-height:420px}[data-template-role="windows"] article{position:absolute;width:48%;height:180px}[data-template-role="windows"] article:nth-child(2){left:36%;top:70px;transform:rotate(3deg)}[data-template-role="windows"] article:nth-child(3){left:12%;top:210px;transform:rotate(-2deg)}' },
  exhibit: { family:'exhibit', background:'#151418', surface:'#26232b', ink:'#f8f4ed', muted:'#a49da6', border:'rgba(255,255,255,.22)', shadow:'0 30px 70px rgba(0,0,0,.42)', radius:'3px', font:'Helvetica,Arial,sans-serif', roles:['navigation','hero','stage','primary-action'], forbidden:['flat admin page','small equal thumbnails'], extra:'[data-template-role="stage"]{grid-template-columns:1.25fr 1fr .8fr;overflow:hidden;perspective:900px}[data-template-role="stage"] article{min-height:340px;transform:rotateY(-7deg)}[data-template-role="stage"] article:nth-child(2){transform:translateY(24px) rotateY(5deg)}[data-template-role="stage"] article:nth-child(3){transform:rotateY(-4deg)}' },
  infinitecanvas: { family:'canvas', background:'radial-gradient(circle,rgba(73,64,79,.42) 0 1.6px,transparent 1.8px),#f5f2ec', surface:'#fffefa', ink:'#211d25', muted:'#716a74', border:'rgba(33,29,37,.22)', shadow:'0 18px 40px rgba(35,29,40,.15)', radius:'14px', font:'Inter,Arial,sans-serif', roles:['navigation','canvas','hero','primary-action'], forbidden:['single fixed column','missing orientation cues'], extra:'body{background-size:24px 24px}[data-template-role="canvas"]{position:relative;min-height:760px;display:block}[data-template-role="canvas"] article{position:absolute;width:28%}[data-template-role="canvas"] article:nth-of-type(1){left:3%;top:34%}[data-template-role="canvas"] article:nth-of-type(2){right:3%;top:20%}[data-template-role="canvas"] article:nth-of-type(3){left:39%;bottom:7%}' },
  ambientcarousel: { family:'carousel', background:'radial-gradient(circle at 20% 20%,#8f70ff,transparent 40%),radial-gradient(circle at 80% 70%,#ff987a,transparent 42%),#eee8df', surface:'rgba(255,255,255,.52)', ink:'#17151a', muted:'#625c63', border:'rgba(255,255,255,.74)', shadow:'0 24px 55px rgba(35,25,45,.22)', radius:'26px', font:'Helvetica,Arial,sans-serif', roles:['ambient-field','navigation','hero','carousel','primary-action'], forbidden:['static equal grid','unrelated background color'], extra:'[data-template-role="carousel"]{display:flex;justify-content:center;perspective:1000px;overflow:hidden}[data-template-role="carousel"] article{flex:0 0 34%;min-height:360px;backdrop-filter:blur(16px);transform:translateX(-12%) rotateY(12deg)}[data-template-role="carousel"] article:nth-child(2){z-index:2;transform:scale(1.08)}[data-template-role="carousel"] article:nth-child(3){transform:translateX(12%) rotateY(-12deg)}' },
  ascii: { family:'ascii', background:'#0d1010', surface:'#121715', ink:'#d8ff73', muted:'#829b4e', border:'#62772f', shadow:'0 0 30px rgba(216,255,115,.09)', radius:'0px', font:'ui-monospace,monospace', roles:['navigation','hero','raster','primary-action'], forbidden:['photographic image dependency','low-contrast raster'], extra:'main{grid-template-columns:.75fr 1.25fr;align-items:center}[data-template-role="raster"]{min-height:460px;display:grid;place-items:center;padding:24px;background:repeating-linear-gradient(0deg,transparent 0 4px,rgba(216,255,115,.05) 4px 5px);font-size:clamp(12px,2vw,24px);white-space:pre-wrap}' },
};

function buildCss(id: string, definition: CapsuleDefinition) {
  const scope = `[data-compose-template="${id}"]`;
  return `${scope}{--template-bg:${definition.background};--template-surface:${definition.surface};--template-ink:${definition.ink};--template-muted:${definition.muted};--template-border:${definition.border};--template-shadow:${definition.shadow};--template-radius:${definition.radius};margin:0;min-height:100vh;padding:24px;background:var(--template-bg);color:var(--template-ink);font-family:${definition.font}}${scope} *{box-sizing:border-box}${scope} header,${scope} main,${scope} section,${scope} article{min-width:0}${scope}>header,${scope} [data-template-role="navigation"]{display:flex;align-items:center;justify-content:space-between;gap:16px;max-width:1440px;margin:0 auto 20px;padding:14px 16px;border:1px solid var(--template-border);border-radius:var(--template-radius);background:var(--template-surface);box-shadow:var(--template-shadow)}${scope} main{display:grid;gap:20px;max-width:1440px;margin:auto}${scope} [data-template-role="hero"]{display:grid;gap:14px;padding:clamp(34px,6vw,86px) 0}${scope} h1{margin:0;letter-spacing:-.06em;line-height:.9}${scope} p{max-width:66ch;color:var(--template-muted)}${scope} [data-template-role="content"],${scope} [data-template-role="metrics"],${scope} [data-template-role="board"],${scope} [data-template-role="gallery"],${scope} [data-template-role="controls"],${scope} [data-template-role="stage"]{display:grid;gap:16px}${scope} article,${scope} [data-template-role="table"],${scope} [data-template-role="story"]{padding:20px;border:1px solid var(--template-border);border-radius:var(--template-radius);background:var(--template-surface);box-shadow:var(--template-shadow)}${scope} button,${scope} [data-template-role="primary-action"]{min-height:44px;padding:0 18px;border:1px solid var(--template-border);border-radius:var(--template-radius);background:var(--compose-accent,var(--template-ink));color:var(--compose-accent-contrast,#fff);font:inherit;font-weight:700;cursor:pointer}${scope} a{color:inherit}${scope} ${definition.extra}@media(max-width:720px){${scope}{padding:12px}${scope} [data-template-role="content"],${scope} [data-template-role="metrics"],${scope} [data-template-role="board"],${scope} [data-template-role="gallery"],${scope} [data-template-role="stage"],${scope} main{grid-template-columns:1fr!important}${scope} [data-template-role="windows"] article,${scope} [data-template-role="canvas"] article{position:relative!important;inset:auto!important;width:100%!important;margin-bottom:12px;transform:none!important}${scope} [data-template-role="carousel"]{display:grid!important}${scope} [data-template-role="carousel"] article{transform:none!important}}@media(prefers-reduced-motion:reduce){${scope} *,${scope} *:before,${scope} *:after{animation:none!important;transition-duration:.01ms!important;transform:none!important}}`;
}

export const templateGenerationCapsules = Object.fromEntries(Object.entries(definitions).map(([id, definition]) => [id, {
  id,
  family: definition.family,
  requiredRoles: definition.roles,
  forbidden: definition.forbidden,
  htmlSkeleton: skeletons[definition.family],
  cssFoundation: buildCss(id, definition),
}])) as Record<string, TemplateGenerationCapsule>;

export function getTemplateGenerationCapsule(id: unknown) {
  return templateGenerationCapsules[String(id)] || templateGenerationCapsules.minimal;
}

export function hasTemplateSignature(html: string, capsule: TemplateGenerationCapsule) {
  const family = new RegExp(`data-template-family=["']${capsule.family}["']`, 'i').test(html);
  const roles = capsule.requiredRoles.every((role) => new RegExp(`data-template-role=["']${role}["']`, 'i').test(html));
  return family && roles;
}

export function applyTemplateCapsule(html: string, capsule: TemplateGenerationCapsule) {
  const style = `<style id="compose-template-capsule" data-template="${capsule.id}">${capsule.cssFoundation}</style>`;
  return html
    .replace(/<body([^>]*)>/i, `<body$1 data-compose-template="${capsule.id}">`)
    .replace(/<\/head>/i, `${style}</head>`);
}
